### PR TITLE
feat: add dockefile

### PR DESCRIPTION
**Pull request by GabrielBdeC**
This pull request aims to add a dockerfile with installation of docker
It can be configurable using environment variables to self signed certificates, ports and secret pass

I'll create a pull request for the plugin integrating with this image too

### CODE REVIEW

**Comment by jeroenhabets** [comment]
@jcrodriguez-dis I would also be very interested in using Docker as an installation method. What are your thoughts on this PR by @GabrielBdeC ?

**Comment by kristian-94** [comment]
Thanks for your work on this, it'll be very useful to use this image rather than manually installing everything. Do you have a prebuilt image on docker hub already that we can use in the meantime?  

That's because when running this build on my machine (m1 macbook with `docker build -t vpl-jail --platform linux/amd64 .`) I get an error, looks like when installing `mono-complete` 
```
Updating Mono key store
122.6 TYPE: 6
122.6 V: mono_thread_interruption_checkpoint
122.6 * Assertion at ../../mono/arch/amd64/../x86/x86-codegen.h:410, condition `offset == (gint32)offset' not met
```

**Comment by GabrielBdeC** [comment]
@kristian-94: https://hub.docker.com/r/gabrielbdec/vpl-jail

**Comment by jeroenhabets** [comment]
> That's because when running this build on my machine (m1 macbook with docker build -t vpl-jail --platform linux/amd64 .) I get an error, looks like when installing mono-complete

P.S. @kristian-94 I had run into that myself and had already logged a request to replace mono with dotnet: https://github.com/jcrodriguez-dis/vpl-xmlrpc-jail/issues/67

**Comment by jeroenhabets** [comment]
@jcrodriguez-dis in full appreciation of your work, would you be able to share what is stopping you from progressing on this? Anything we can do to help?

**Comment by jcrodriguez-dis** [comment]
Thank you to all contributors, especially @GabrielBdeC, for your valuable insights and efforts. As someone initially unfamiliar with Docker, I faced challenges in evaluating and integrating the suggested modifications. Nevertheless, recognizing Docker's importance has led to significant enhancements in VPL's functionality. I am excited to announce that VPL version 4.0.0 now fully supports Docker, offering diverse configurations, including support for certificates from Let's Encrypt. For more details, please refer to the release notes. A comprehensive manual will be available soon.

- **Issue with Mono**: In VPL version 4.0.0, the jail installer has been updated. We now utilize external files listing the packages required for different package managers: APT, DNF, and APK. The format for each line in these files is:
  `"Human-readable name" package1 package2 package3`
  Each line installs the first available package from the list. As I am not an expert in .NET, I am unsure whether adding .NET packages necessitates changes to the compiler or run launcher in the VPL Moodle plugin.

Your ongoing contributions and feedback are integral to VPL's continuous development and improvement. Thank you for your commitment and support.

**Comment by jeroenhabets** [comment]
@jcrodriguez-dis, @GabrielBdeC would it not be better/clearer to now close this [PR](https://github.com/jcrodriguez-dis/vpl-jail-system/pull/64) (abandon it _without_ merging) as [VPL version 4.0.0](https://github.com/jcrodriguez-dis/vpl-jail-system/releases/tag/V4.0.0) now fully supports Docker?

(See also previous comment by @jcrodriguez-dis https://github.com/jcrodriguez-dis/vpl-jail-system/pull/64#issuecomment-1863607637)
> I am excited to announce that VPL version 4.0.0 now fully supports Docker

**Pull request closed without merging**
